name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8 (ignoring E501)
        run: |
          pip install flake8
          flake8 --ignore=E501 .

  test:
    name: Run Automated Tests & Security Scans
    runs-on: ubuntu-latest
    needs: build
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run Integration Tests
        run: |
          pytest tests/integration

      - name: Run Security Scan
        run: |
          pip install bandit
          bandit -r .

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying the application..."
          # Replace the commands below with your actual deployment steps.
          echo "Deployment complete!"
