name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # --------------------------
      # Build Stage
      # --------------------------
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --------------------------
      # Test Stage
      # --------------------------
      - name: Run Unit Tests (Pytest)
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: monish217/emotion-detect:latest
          push: false  # Build but don't push yet

      - name: Run Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: monish217/emotion-detect:latest

      # --------------------------
      # Deploy Stage
      # --------------------------
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: monish217/emotion-detect:latest
